spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: 8b17dcc3-8425-458d-9f6d-5ad291597945 # Nacos 命名空间 uat 的编号
