spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: 55129d6d-ca72-4080-9c92-f354d1bb9efa # Nacos 命名空间 dev 的编号
